name: Android APK Build

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        working-directory: primal_mobile
        run: flutter pub get

      - name: Build APK
        working-directory: primal_mobile
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: primal_mobile-apk
          path: primal_mobile/build/app/outputs/flutter-apk/app-release.apk