name: Android APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.0'

      - name: Flutter doctor
        working-directory: primal_mobile
        run: flutter doctor -v

      - name: Flutter clean
        working-directory: primal_mobile
        run: flutter clean

      - name: Flutter pub get
        working-directory: primal_mobile
        run: flutter pub get

      - name: Build APK
        working-directory: primal_mobile
        run: flutter build apk --release --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: primal_mobile-apk
          path: primal_mobile/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error